language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

jobs:
  include:
    - php: '7.3'

install:
  - cp etc/travis/env.local .env.local
  - yarn install
  - composer install

script:
- ./bin/phpunit

before_deploy:
- openssl aes-256-cbc -K $encrypted_6041831ee8a2_key -iv $encrypted_6041831ee8a2_iv -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

deploy:
  - provider: script
    script: etc/travis/deploy.sh
    on:
      branch: travis-build
