export const SIAP_TOGGLE_LOADING = "SIAP_TOGGLE_LOADING";
export const SIAP_LOGIN_START = "SIAP_LOGIN_START";
export const SIAP_LOGIN_END = "SIAP_LOGIN_END";
export const SIAP_LOGIN_ERROR = "SIAP_LOGIN_ERROR";
export const SIAP_LOGIN_RESET = "SIAP_LOGIN_RESET";
export const SIAP_SNACKBAR = "SIAP_SNACKBAR";
export const SIAP_TOGGLE_DRAWER = "SIAP_TOGGLE_DRAWER";
