#controllers:
#    resource:
#        path: ../src/User/Controller/
#        namespace: Paroki\User\Controller
#    type: attribute
login:
  path: /login
  methods: ['POST']

core_controllers:
  resource:
    path: ../src/Core/Controller/
    namespace: Paroki\Core\Controller
  type: attribute
